Repository przemekkojs/harmonyio, pull requests merged in 2024-11, with the labels that each got.

#52 Spóźniony PR-widmo
  main/Main/Pages/Creator.cshtml
  main/Main/Pages/Solve.cshtml
  main/Main/wwwroot/js/creator-scripts/addFunctionality.js
  main/Main/wwwroot/js/creator-scripts/component.js
  main/Main/wwwroot/js/creator-scripts/createComponentCreator.js
  main/Main/wwwroot/js/creator-scripts/taskCreator.js
  main/Main/wwwroot/js/creator-scripts/taskEditor.js
Labels: enhancement

#56 Usunięte bounding boxy, dodany hint przy dodawaniu nuty, poprawione rozmiary i pozycje pięciolinii
  main/Main/Pages/Solve.cshtml
  main/Main/wwwroot/images/staff-symbols/forbidden.png
  main/Main/wwwroot/js/staff-scripts/bar.js
  main/Main/wwwroot/js/staff-scripts/constants.js
  main/Main/wwwroot/js/staff-scripts/functionSymbol.js
  main/Main/wwwroot/js/staff-scripts/menu.js
  main/Main/wwwroot/js/staff-scripts/sketchGrading.js
  main/Main/wwwroot/js/staff-scripts/sketchSolving.js
  main/Main/wwwroot/js/staff-scripts/twoNotes.js
  main/Main/wwwroot/js/staff-scripts/vertical.js
Labels: enhancement

#60 Poprawki algorytmu 2 - STARY ALGORYTM ZNIKA NA ZAWSZE
  .gitignore
  algorithm/Algorithm/New/Algorithm/Mistake/FunctionMistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/Mistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/NoteMistake.cs
  algorithm/AlgorithmTests/New/SolutionCheckerTests.cs
Labels: enhancement, wontfix

#61 Integracja algorytmu 1
  main/Main/GradingAlgorithm/GradingAlgorithm.cs
  main/Main/GradingAlgorithm/IGradingAlgorithm.cs
  main/Main/GradingAlgorithm/TestGradingAlgorithm.cs
  main/Main/Main.csproj
  main/Main/Pages/Grade.cshtml.cs
  main/Main/Program.cs
Labels: enhancement, question

#64 Algorytm - zasady podstawowe
  algorithm/Algorithm/New/Algorithm/Checkers/SolutionChecker.cs
  algorithm/Algorithm/New/Algorithm/Mistake/FunctionMistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/Mistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/NoteMistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/StackMistake.cs
  algorithm/Algorithm/New/Algorithm/Rules/DoubledFifthOnStrongBarPart.cs
  algorithm/Algorithm/New/Algorithm/Rules/OneDirection.cs
  algorithm/Algorithm/New/Algorithm/Rules/ParallelFifths.cs
  algorithm/Algorithm/New/Algorithm/Rules/ParallelOctaves.cs
  algorithm/Algorithm/New/Algorithm/Rules/Rule.cs
  algorithm/Algorithm/New/Algorithm/Rules/VoiceCrossing.cs
  algorithm/Algorithm/New/Algorithm/Rules/VoiceCrossingOneFunction.cs
  algorithm/Algorithm/New/Utils/Interval.cs
  main/Main/Pages/Creator.cshtml
Labels: enhancement

#65 Responsywność ekranu 2
  main/Main/Pages/Created.cshtml
  main/Main/Pages/Groups/Details.cshtml
  main/Main/Pages/Groups/Index.cshtml
  main/Main/Pages/Shared/AddUsersPopup.cshtml
  main/Main/Pages/Shared/AssignPopup.cshtml
  main/Main/Pages/Shared/CreateGroupPopup.cshtml
  main/Main/Pages/Shared/DeleteGroupPopup.cshtml
  main/Main/Pages/Shared/DeleteQuizPopup.cshtml
  main/Main/Pages/Shared/DeleteUserPopup.cshtml
  main/Main/Pages/Shared/PublishPopup.cshtml
  main/Main/wwwroot/css/site.css
  main/Main/wwwroot/lib/bootstrap/dist/css/custom.min.css
Labels: enhancement

#66 Poprawka ładowania zadań
  main/Main/Pages/Creator.cshtml
  main/Main/wwwroot/js/creator-scripts/addFunctionality.js
  main/Main/wwwroot/js/creator-scripts/component.js
  main/Main/wwwroot/js/creator-scripts/function.js
  main/Main/wwwroot/js/creator-scripts/taskCreator.js
  main/Main/wwwroot/js/creator-scripts/taskEditor.js
Labels: enhancement

#68 małe zmiany w onGet ekranu solve i wyświetlaniu, usunięta pierwsza linia pięciolinii, zmieniony rozmiar menu, poprawiony hint dodawania nuty
  main/Main/Pages/Creator.cshtml.cs
  main/Main/Pages/Index.cshtml
  main/Main/Pages/Solve.cshtml.cs
  main/Main/wwwroot/js/staff-scripts/menu.js
  main/Main/wwwroot/js/staff-scripts/staff.js
  main/Main/wwwroot/js/staff-scripts/twoNotes.js
Labels: enhancement

#69 Ładowanie istniejących zadań do kreatora funkcji 2
  main/Main/Pages/Creator.cshtml
  main/Main/Pages/Creator.cshtml.cs
  main/Main/wwwroot/js/creator-scripts/addFunctionality.js
  main/Main/wwwroot/js/creator-scripts/barContainer.js
  main/Main/wwwroot/js/creator-scripts/createComponentCreator.js
  main/Main/wwwroot/js/creator-scripts/functionContainer.js
  main/Main/wwwroot/js/creator-scripts/functionCreator.js
  main/Main/wwwroot/js/creator-scripts/parsedFunction.js
  main/Main/wwwroot/js/creator-scripts/taskContainer.js
  main/Main/wwwroot/js/creator-scripts/taskCreator.js
  main/Main/wwwroot/js/creator-scripts/taskEditor.js
Labels: bug, enhancement

#71 Poprawki algorytmu 1
  algorithm/Algorithm/New/Algorithm/Checkers/SolutionChecker.cs
  algorithm/Algorithm/New/Algorithm/Mistake/Mistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/NoteMistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/StackMistake.cs
  algorithm/Algorithm/New/Algorithm/Parsers/NoteParser/Parser.cs
  algorithm/Algorithm/New/Algorithm/Parsers/SolutionParser/Parser.cs
  algorithm/Algorithm/New/Algorithm/Rules/DoubledFifthOnStrongBarPart.cs
  algorithm/Algorithm/New/Algorithm/Rules/OneDirection.cs
  algorithm/Algorithm/New/Algorithm/Rules/ParallelFifths.cs
  algorithm/Algorithm/New/Algorithm/Rules/ParallelOctaves.cs
  algorithm/Algorithm/New/Algorithm/Rules/Rule.cs
  algorithm/Algorithm/New/Algorithm/Rules/VoiceCrossing.cs
  algorithm/Algorithm/New/Algorithm/Rules/VoiceCrossingOneFunction.cs
  algorithm/Algorithm/New/Music/Stack.cs
  main/Main/Pages/Creator.cshtml
  main/Main/Pages/Solve.cshtml
  main/Main/wwwroot/js/creator-scripts/functionCreator.js
Labels: enhancement

#81 Opisy algorytmu 2
  algorithm/Algorithm/New/Algorithm/Mistake/NoteMistake.cs
  algorithm/Algorithm/New/Algorithm/Rules/DoubledFifthOnStrongBarPart.cs
  algorithm/Algorithm/New/Algorithm/Rules/OneDirection.cs
  algorithm/Algorithm/New/Algorithm/Rules/ParallelFifths.cs
  algorithm/Algorithm/New/Algorithm/Rules/ParallelOctaves.cs
  algorithm/Algorithm/New/Algorithm/Rules/Rule.cs
  algorithm/Algorithm/New/Algorithm/Rules/VoiceCrossing.cs
  algorithm/Algorithm/New/Algorithm/Rules/VoiceCrossingOneFunction.cs
  algorithm/Algorithm/New/Constants.cs
  algorithm/Algorithm/New/Music/Stack.cs
  main/Main/GradingAlgorithm/GradingAlgorithm.cs
  main/Main/wwwroot/css/site.css
Labels: enhancement, invalid, question

#85 Walidacja kreatora 1
  algorithm/Algorithm/Algorithm.csproj
  algorithm/Algorithm/New/Algorithm/Checkers/ProblemChecker.cs
  algorithm/Algorithm/New/Algorithm/Checkers/SolutionChecker.cs
  algorithm/Algorithm/New/Algorithm/Mistake/Problem/ProblemMistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/Solution/Mistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/Solution/NoteMistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/Solution/StackMistake.cs
  algorithm/Algorithm/New/Algorithm/Rules/Problem/Rule.cs
  algorithm/Algorithm/New/Algorithm/Rules/Problem/SubdominantAfterDominant.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/DoubledFifthOnStrongBarPart.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/OneDirection.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/ParallelFifths.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/ParallelOctaves.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/Rule.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/VoiceCrossing.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/VoiceCrossingOneFunction.cs
  algorithm/Algorithm/New/Algorithm/Settings.cs
  algorithm/Algorithm/New/Algorithm/Solution.cs
  algorithm/Algorithm/New/Constants.cs
  algorithm/Algorithm/New/Music/Function.cs
  algorithm/Algorithm/New/Music/Tonation.cs
  algorithm/Algorithm/Old/Music/Interval.cs
  main/Main/GradingAlgorithm/GradingAlgorithm.cs
  main/Main/Pages/Creator.cshtml.cs
Labels: enhancement, help wanted

#90 Walidacja kreatora zadań
  main/Main/Pages/Creator.cshtml
  main/Main/Pages/Creator.cshtml.cs
  main/Main/wwwroot/js/creator-scripts/functionCreator.js
Labels: enhancement

#93 Zmiana logiki punktowania zadań 1
  algorithm/Algorithm/New/Algorithm/Parsers/ProblemParser/JsonProblem.cs
  algorithm/Algorithm/New/Algorithm/Parsers/ProblemParser/Parser.cs
  algorithm/Algorithm/New/Algorithm/Problem.cs
  main/Main/GradingAlgorithm/GradingAlgorithm.cs
  main/Main/Main.csproj.user
  main/Main/Migrations/20241019090414_InitialCreate.Designer.cs
  main/Main/Migrations/20241021174631_added-quiz-codes.Designer.cs
  main/Main/Migrations/20241021174631_added-quiz-codes.cs
  main/Main/Migrations/20241022132829_AddedGradeDate.Designer.cs
  main/Main/Migrations/20241022132829_AddedGradeDate.cs
  main/Main/Migrations/20241026194151_AddedUserGroupsAndGroupRequests.Designer.cs
  main/Main/Migrations/20241026194151_AddedUserGroupsAndGroupRequests.cs
  main/Main/Migrations/20241029151126_quizPublishedToData.Designer.cs
  main/Main/Migrations/20241029151126_quizPublishedToData.cs
  main/Main/Migrations/20241029181607_jsonConvertingForQuizPublishedTo.Designer.cs
  main/Main/Migrations/20241029181607_jsonConvertingForQuizPublishedTo.cs
  main/Main/Migrations/20241103015658_groupMasterCreator.Designer.cs
  main/Main/Migrations/20241103015658_groupMasterCreator.cs
  main/Main/Migrations/20241108153218_RemovedRolesQuizzesSharedToUsersNotMails.Designer.cs
  main/Main/Migrations/20241108153218_RemovedRolesQuizzesSharedToUsersNotMails.cs
  main/Main/Migrations/20241108161012_PublishedToUsersRemovedUsingParticipantsInstead.Designer.cs
  main/Main/Migrations/20241108161012_PublishedToUsersRemovedUsingParticipantsInstead.cs
  main/Main/Migrations/20241108171035_RemovedaRequestExpiration.Designer.cs
  main/Main/Migrations/20241108171035_RemovedaRequestExpiration.cs
  main/Main/Migrations/20241109110543_RemoveExpirationDate.Designer.cs
  main/Main/Migrations/20241109110543_RemoveExpirationDate.cs
  main/Main/Migrations/20241111112036_removinExpirationDateForRealThisTime.cs
  main/Main/Migrations/20241113203419_InitialCreate.Designer.cs
  main/Main/Migrations/20241113203419_InitialCreate.cs
  main/Main/Migrations/ApplicationDbContextModelSnapshot.cs
  main/Main/Models/Excersise.cs
  main/Main/Models/ExcersiseResult.cs
  main/Main/Models/Quiz.cs
  main/Main/Pages/Creator.cshtml
  main/Main/Pages/Creator.cshtml.cs
  main/Main/Pages/Grade.cshtml
  main/Main/Pages/Grade.cshtml.cs
  main/Main/Pages/Solve.cshtml.cs
  main/Main/wwwroot/css/creator-style.css
  main/Main/wwwroot/css/function-creator-styles.css
  main/Main/wwwroot/js/creator-scripts/taskContainer.js
  main/Main/wwwroot/js/utils.js
Labels: enhancement

#100 Opisy algorytmu 3
  algorithm/Algorithm/New/Algorithm/Checkers/SolutionChecker.cs
  algorithm/Algorithm/New/Algorithm/Mistake/Solution/Mistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/Solution/NoteMistake.cs
  algorithm/Algorithm/New/Algorithm/Mistake/Solution/StackMistake.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/DoubledFifthOnStrongBarPart.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/OneDirection.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/ParallelFifths.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/ParallelOctaves.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/Rule.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/VoiceCrossing.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/VoiceCrossingOneFunction.cs
  main/Main/Data/ApplicationDbContext.cs
  main/Main/Data/ApplicationRepository.cs
  main/Main/GradingAlgorithm/GradingAlgorithm.cs
  main/Main/Models/MistakeResult.cs
  main/Main/Pages/Grade.cshtml
  main/Main/Pages/Grade.cshtml.cs
  main/Main/Pages/Solve.cshtml.cs
Labels: enhancement

#107 Informowanie o błędnych quizach
  main/Main/Pages/Created.cshtml
  main/Main/Pages/Created.cshtml.cs
  main/Main/wwwroot/js/creator-scripts/functionContainer.js
Labels: enhancement

#113 Unit tests for join, browse and groups index. Fix queries
  main/Main.Tests/AssignedTests.cs
  main/Main.Tests/BrowseTests.cs
  main/Main.Tests/GroupsIndexTests.cs
  main/Main.Tests/JoinTests.cs
  main/Main/Data/ApplicationRepository.cs
  main/Main/Migrations/20241122100312_AddBrowseAlgorithmShow.cs
  main/Main/Migrations/20241122144126_InitialMigrationSqlServer.Designer.cs
  main/Main/Migrations/20241122164854_Initial.Designer.cs
  main/Main/Migrations/20241122164854_Initial.cs
  main/Main/Pages/Assigned.cshtml.cs
  main/Main/Pages/Browse.cshtml.cs
  main/Main/Pages/Grade.cshtml
  main/Main/Pages/Grade.cshtml.cs
  main/Main/Pages/Groups/Index.cshtml
  main/Main/Pages/Groups/Index.cshtml.cs
  main/Main/Pages/Join.cshtml.cs
  main/Main/Pages/Solve.cshtml.cs
Labels: enhancement, question

#115 Integracja generatora zadań
  algorithm/Algorithm/New/Algorithm/Checkers/SolutionChecker.cs
  algorithm/Algorithm/New/Algorithm/Checkers/StackPairChecker.cs
  algorithm/Algorithm/New/Algorithm/Generators/ProblemGenerator.cs
  algorithm/Algorithm/New/Algorithm/Generators/SolutionGenerator.cs
  algorithm/Algorithm/New/Algorithm/Parsers/ProblemParser/JsonProblem.cs
  algorithm/Algorithm/New/Algorithm/Parsers/ProblemParser/Parser.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/OneDirection.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/ParallelFifths.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/ParallelOctaves.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/VoiceCrossing.cs
  algorithm/Algorithm/New/Algorithm/Rules/Solution/VoiceCrossingOneFunction.cs
  algorithm/Algorithm/New/Constants.cs
  algorithm/Algorithm/New/Music/Component.cs
  algorithm/Algorithm/New/Music/Function.cs
  algorithm/Algorithm/New/Utils/Combinations.cs
  algorithm/Algorithm/New/Utils/Permutations.cs
  algorithm/AlgorithmTests/New/FunctionParsingTests.cs
  algorithm/AlgorithmTests/New/SolutionCheckerTests.cs
  algorithm/AlgorithmTests/New/SolutionGeneratorTests.cs
  algorithm/AlgorithmTests/New/SolutionParserTests.cs
  main/Main/Migrations/20241122171217_InitAfterCrash.Designer.cs
  main/Main/Migrations/20241122171217_InitAfterCrash.cs
  main/Main/Pages/Browse.cshtml.cs
  main/Main/Pages/Creator.cshtml
  main/Main/Pages/Creator.cshtml.cs
  main/Main/wwwroot/js/creator-scripts/barContainer.js
  main/Main/wwwroot/js/creator-scripts/functionContainer.js
  main/Main/wwwroot/js/creator-scripts/functionCreator.js
  main/Main/wwwroot/js/creator-scripts/taskContainer.js
Labels: enhancement

#116 Poprawa opisów algorytmu
  algorithm/Algorithm/New/Algorithm/Checkers/SolutionChecker.cs
  main/Main/GradingAlgorithm/GradingAlgorithm.cs
  main/Main/Migrations/20241122164854_Initial.Designer.cs
  main/Main/Migrations/20241122171217_InitAfterCrash.cs
  main/Main/Migrations/20241125113822_MoveShowAlgorithmOpinionToQuiz.Designer.cs
  main/Main/Migrations/20241125113822_MoveShowAlgorithmOpinionToQuiz.cs
  main/Main/Migrations/20241125221720_ThirdInit.Designer.cs
  main/Main/Migrations/20241125221720_ThirdInit.cs
  main/Main/Pages/Browse.cshtml.cs
  main/Main/Pages/Grade.cshtml.cs
  main/Main/Pages/Solve.cshtml.cs
  main/Main/Utils/Utils.cs
Labels: enhancement

#121 Integracja generacji zadań
  algorithm/Algorithm/New/Algorithm/Generators/SolutionGenerator.cs
  algorithm/Algorithm/New/Algorithm/Parsers/SolutionParser/Parser.cs
  main/Main/Models/Excersise.cs
  main/Main/Pages/Browse.cshtml
  main/Main/Pages/Browse.cshtml.cs
Labels: enhancement

#127 Integracja przeglądania rozwiązania algorytmu
  algorithm/Algorithm/New/Algorithm/Generators/SolutionGenerator.cs
  algorithm/Algorithm/New/Algorithm/Parsers/SolutionParser/Parser.cs
  algorithm/Algorithm/New/Constants.cs
  algorithm/Algorithm/New/Utils/Rhytm.cs
  algorithm/AlgorithmTests/New/RhytmizerTests.cs
  main/Main/Pages/Browse.cshtml
  main/Main/wwwroot/js/creator-scripts/barContainer.js
  main/Main/wwwroot/js/creator-scripts/functionContainer.js
  main/Main/wwwroot/js/creator-scripts/taskContainer.js
Labels: enhancement

#130 Integracja kodów QR
  .gitignore
  algorithm/AlgorithmTests/New/SolutionCheckerTests.cs
  main/Main/GradingAlgorithm/GradingAlgorithm.cs
  main/Main/Main.csproj
  main/Main/Main.sln
  main/Main/Pages/Browse.cshtml
  main/Main/Pages/Browse.cshtml.cs
  main/Main/Pages/Created.cshtml
  main/Main/Pages/Creator.cshtml
  main/Main/Pages/Shared/AssignPopup.cshtml
  main/Main/wwwroot/images/qr-code.png
  main/Main/wwwroot/js/midi-player-scripts/MIDI_sample.mid
  main/Main/wwwroot/js/midi-player-scripts/midiplayer.js
  main/Main/wwwroot/js/midi-player-scripts/soundfont-player.min.js
  midi/MidiPlayback/FileCreator.cs
  midi/MidiPlayback/MidiPlayback.csproj
  midi/MidiPlayback/MidiPlayback.sln
  midi/MidiPlaybackTests/FileCreateTests.cs
  midi/MidiPlaybackTests/MidiPlaybackTests.csproj
Labels: enhancement, wontfix
